### ISSUE TITLE
blog page returns error 500 on 5.2 beta4

### ISSUE THREAD

**Issue by RobertoPorcar** [yuzoolcode/pulsecms-tracking#63]
Clean install.

HTTP ERROR 500

I can send ftp credentials for debugging.

**Comment by ghost** [comment]
Can you attach the logs?

This should have been fixed in B4

(related to: https://forum.pulsecms.com/t/pulse-5-2beta4-release/1181/11)

**Comment by RobertoPorcar** [comment]
`error_log_2018_11_15
[15-Nov-2018 17:30:32 Asia/Tokyo] PHP Warning: fileperms(): stat failed for /home/hayclase/public_html/pulsecore/storage/config.json in /home/hayclase/public_html/admin/install.php on line 296
[15-Nov-2018 17:30:40 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/wedge/config.php(200): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/hayclase/public_html/pulsecore/install/config.php(97): pulsecore\wedge\config\load_config('/home/hayclase/...')
#2 /home/hayclase/public_html/admin/install.php(46): pulsecore\install\config_update_json('/home/hayclase/...', Array)
#3 {main}
thrown in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:30:54 Asia/Tokyo] PHP Warning: fileperms(): stat failed for /home/hayclase/public_html/pulsecore/storage/config.json in /home/hayclase/public_html/admin/install.php on line 296
[15-Nov-2018 17:30:55 Asia/Tokyo] PHP Warning: fileperms(): stat failed for /home/hayclase/public_html/pulsecore/storage/config.json in /home/hayclase/public_html/admin/install.php on line 296
[15-Nov-2018 17:31:03 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/wedge/config.php(200): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/hayclase/public_html/pulsecore/install/config.php(97): pulsecore\wedge\config\load_config('/home/hayclase/...')
#2 /home/hayclase/public_html/admin/install.php(46): pulsecore\install\config_update_json('/home/hayclase/...', Array)
#3 {main}
thrown in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:31:08 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/wedge/config.php(200): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/hayclase/public_html/pulsecore/wedge/config.php(242): pulsecore\wedge\config\load_config('/home/hayclase/...')
#2 /home/hayclase/public_html/config.php(72): pulsecore\wedge\config\wedge_config()
#3 /home/hayclase/public_html/admin/index.php(10): require_once('/home/hayclase/...')
#4 {main}
thrown in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:31:25 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/wedge/config.php(200): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/hayclase/public_html/pulsecore/wedge/config.php(242): pulsecore\wedge\config\load_config('/home/hayclase/...')
#2 /home/hayclase/public_html/config.php(72): pulsecore\wedge\config\wedge_config()
#3 /home/hayclase/public_html/admin/index.php(10): require_once('/home/hayclase/...')
#4 {main}
thrown in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:31:28 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/wedge/config.php(200): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/hayclase/public_html/pulsecore/wedge/config.php(242): pulsecore\wedge\config\load_config('/home/hayclase/...')
#2 /home/hayclase/public_html/config.php(72): pulsecore\wedge\config\wedge_config()
#3 /home/hayclase/public_html/index.php(7): require_once('/home/hayclase/...')
#4 {main}
thrown in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:34:54 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:34:54 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:35:53 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:35:53 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:36:55 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:36:55 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:41:46 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:41:46 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:41:51 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:41:51 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:44:34 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:44:34 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 17:44:43 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 17:44:43 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 19:01:08 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 19:01:08 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 19:53:31 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 19:53:31 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 19:53:47 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 19:53:47 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 19:55:52 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 19:55:52 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 20:31:47 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 20:31:47 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 20:32:00 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 20:32:00 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$lang_form_name in /home/hayclase/public_html/inc/tags/form.php on line 171
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$lang_form_name in /home/hayclase/public_html/inc/tags/form.php on line 172
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$mail_inputs in /home/hayclase/public_html/inc/tags/form.php on line 173
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Trying to get property of non-object in /home/hayclase/public_html/inc/tags/form.php on line 173
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$lang_form_email in /home/hayclase/public_html/inc/tags/form.php on line 178
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$lang_form_email in /home/hayclase/public_html/inc/tags/form.php on line 179
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$mail_inputs in /home/hayclase/public_html/inc/tags/form.php on line 180
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Trying to get property of non-object in /home/hayclase/public_html/inc/tags/form.php on line 180
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$mail_inputs in /home/hayclase/public_html/inc/tags/form.php on line 187
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Trying to get property of non-object in /home/hayclase/public_html/inc/tags/form.php on line 187
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$mail_textarea in /home/hayclase/public_html/inc/tags/form.php on line 220
[15-Nov-2018 20:32:29 Asia/Tokyo] PHP Notice: Trying to get property of non-object in /home/hayclase/public_html/inc/tags/form.php on line 220
[15-Nov-2018 20:32:51 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 20:32:51 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12
[15-Nov-2018 20:44:52 Asia/Tokyo] PHP Notice: Undefined property: stdClass::$result_per_page in /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php on line 24
[15-Nov-2018 20:44:52 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/hayclase/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/hayclase/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/hayclase/public_html/pulsecore/tags/blog_content_loop.php(37): pulsecore\pre_condition(false)
#2 /home/hayclase/public_html/inc/tags/blog-content-loop.php(15): pulsecore\tags\BlogContentLoop->generate_html(Array, Array)
#3 /home/hayclase/public_html/inc/tags/blog-content-loop.php(21): tag_blog_content_loop(Array)
#4 /home/hayclase/public_html/pulsecore/tag_runner.php(63): require('/home/hayclase/...')
#5 /home/hayclase/public_html/pulsecore/tag_runner.php(106): pulsecore\tag_runner\expand_single_tag('{{blog-content-...', Array)
#6 /home/hayclase/public_html/pulsecore/tags/blog.php(50): pulsecore\tag_runner\expand('{{featured-imag...', Array)
#7 /home/hayclase/public_html/inc/tags/blog.php(28): pulsecore\tags\Blog->generate_html(Array, Array)
#8 /home/hayclase/public_html/index.php(293): in /home/hayclase/public_html/pulsecore/dbc.php on line 12`

**Comment by RobertoPorcar** [comment]
attached
[log-issue.txt](https://github.com/yuzoolcode/pulsecms-tracking/files/2585139/log-issue.txt)

**Comment by ghost** [comment]
@RobertoPorcar 

Had a look at the log. The result_per_page config option is missing. 

That's because the JSON config isn't being loaded. Its either file permissions again, or the web server cant write/read the file.

Can we recommend you should try setting the "result per page" for the blog items in the admin dashboard under "settings". 

If that fails, its a pretty good sign that the file permissions/ownership needs to be adjusted.

Permissions look OK - I think its likely to be the ownership then. At the least the configs, content and htaccess should either be owned by the web server user, or the group (and then the group write permission should be on), last option is to have the files writable by everyone.

**Comment by ghost** [comment]
Roberto said:

> I have discovered that I have to switch theme from pulse settings- extend and save to get the blog working.
> 
> After this I can set the default theme again and seems to work fine.

https://forum.pulsecms.com/t/pulse-5-2beta4-release/1181/14?u=pulsecms

**Comment by ghost** [comment]
Unless theres a bug in the theme for this one?

Changing the template updates the config.json which adds the missing result_per_page option. So that would work.

I checked both template templates and there's no bug in the current code version. I did test removing the config.json and running the installer again. 

We found and fixed a bug in the installer and this might be the solution,

The config.json is saved twice. The first is probably unnecessary so this will be in the next release cling soon.
