### ISSUE TITLE
anomalies in the upload of multimedia content

### ISSUE THREAD

**Issue by ManuelRosique** [yuzoolcode/pulsecms-tracking#70]
I am having anomalies to upload files in the multimedia area, either JPGE, PDF or ZIP.

When I upload a larger file, (1.5 MB for example), the pulse seems to process it, and the load icon becomes the "checkmark". Everything seems fine, but the file is not in view.

this problem had already been solved with the host configuration, but it has reappeared, I have reviewed the hosting configuration, but it is still intact, it is still the same.

![6](https://user-images.githubusercontent.com/45614105/49488087-d4e5ee00-f80a-11e8-8ae5-8fa6201c6e13.png)

Any suggestions for this setback
I am using the version of pulsecms 5.1 with blocsapp 2

**Comment by ghost** [comment]
Thanks for the bug report @ManuelRosique 

This update bug is the POST_MAX_FILESIZE and UPLOAD_MAX_FILESIZE settings related most likely. There are in the htaccess file. Most likely these were changed or overwritten which is why it has changed.

Lines 2 and 3 in the .htaccess need to be uncommented for the upload to work.  

Please try this

**Comment by ManuelRosique** [comment]
I understand but where I modify that file, where do I find it? and how do I edit it?

**Comment by ghost** [comment]
It should be on your server. Called ".htaccess"

If not, use sample.htaccess and make it .htaccess

What FTP programme are you using? Make sure to "show hidden files" so you can see it!

![2018-12-06 at 09 29](https://user-images.githubusercontent.com/4608547/49553138-9ac73a00-f939-11e8-9dae-7cb677df5e2c.jpg)

**Comment by ManuelRosique** [comment]
this is what is inside the file!

![captura de pantalla 2018-12-05 a la s 9 44 34 p m](https://user-images.githubusercontent.com/45614105/49560211-15ab3900-f8d7-11e8-9bde-3262f7f7ad97.png)

I have no idea what I have to change! or leave without comments!

**Comment by ghost** [comment]
It looks like you already have more than these values in your file:

> php_value upload_max_filesize 20M
> php_value post_max_size 25M

Your host seems to have added them there.

- As it was working before (but not anymore).. can you ask them why? 
- Who do you host with? 
- Can you edit the php.ini file (ask them)?

Please explain to your hosts that there is a browser upload timeout happening and ask if they know why. Also check in the Pulse logs (settings > Extend > logs) for any clues. You could attach them here.

**Comment by ManuelRosique** [comment]
php_value upload_max_filesize 20M 
php_value post_max_size 25M

those values ​​and change them! to 100M and 128M, I can edit the php.ini, I do not understand what I need to do? This is what marks today's record!

error_log_2018_12_06
[05-Dec-2018 20:38:11 America/Mexico_City] PHP Notice: Undefined property: stdClass::$max_session_time in /home/bebikeli/public_html/admin/inc/login.php on line 150
[05-Dec-2018 20:38:17 America/Mexico_City] PHP Notice: Undefined property: stdClass::$max_session_time in /home/bebikeli/public_html/admin/inc/login.php on line 150
[05-Dec-2018 20:58:04 America/Mexico_City] PHP Notice: Undefined index: path in /home/bebikeli/public_html/pulsecore/view/helper/body_tag.php on line 43
[05-Dec-2018 20:58:15 America/Mexico_City] PHP Notice: Undefined index: path in /home/bebikeli/public_html/pulsecore/view/helper/body_tag.php on line 43
[05-Dec-2018 20:58:31 America/Mexico_City] PHP Notice: Undefined index: path in /home/bebikeli/public_html/pulsecore/view/helper/body_tag.php on line 43
[05-Dec-2018 20:58:52 America/Mexico_City] PHP Notice: Undefined index: path in /home/bebikeli/public_html/pulsecore/view/helper/body_tag.php on line 43
[05-Dec-2018 23:38:36 America/Mexico_City] PHP Notice: Undefined index: HTTP_ACCEPT_LANGUAGE in /home/bebikeli/public_html/admin/inc/tracker.php on line 52
[05-Dec-2018 23:38:37 America/Mexico_City] PHP Fatal error: Uncaught exception 'LogicException' with message 'A pre-condition has failed' in /home/bebikeli/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/bebikeli/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/bebikeli/public_html/pulsecore/logic/user_agent.php(209): pulsecore\pre_condition(false)
#2 /home/bebikeli/public_html/admin/inc/tracker.php(58): pulsecore\logic\UserAgent->process(Array)
#3 /home/bebikeli/public_html/admin/inc/tracker.php(159): admin_plugin_tracker(Array, Array)
#4 {main}
thrown in /home/bebikeli/public_html/pulsecore/dbc.php on line 12
[05-Dec-2018 23:38:37 America/Mexico_City] PHP Notice: Undefined index: HTTP_ACCEPT_LANGUAGE in /home/bebikeli/public_html/admin/inc/tracker.php on line 52
[05-Dec-2018 23:38:37 America/Mexico_City] PHP Fatal error: Uncaught exception 'LogicException' with message 'A pre-condition has failed' in /home/bebikeli/public_html/pulsecore/dbc.php:12
Stack trace:
#0 /home/bebikeli/public_html/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/bebikeli/public_html/pulsecore/logic/user_agent.php(209): pulsecore\pre_condition(false)
#2 /home/bebikeli/public_html/admin/inc/tracker.php(58): pulsecore\logic\UserAgent->process(Array)
#3 /home/bebikeli/public_html/admin/inc/tracker.php(159): admin_plugin_tracker(Array, Array)
#4 {main}
thrown in /home/bebikeli/public_html/pulsecore/dbc.php on line 12

**Comment by ghost** [comment]
The log doesn't show any errors related to this. 

- Did you try an upload?
- Then check the log again.

Then please:
- As it was working before (but not anymore).. can you ask them why?
- Who do you host with?

**Comment by ghost** [comment]
Tested and MP3s are uploading ok in vanilla installs
