### ISSUE TITLE
admin loggin user out quickly

### ISSUE THREAD

**Issue by pulsecmsuser** [yuzoolcode/pulsecms-tracking#74]
using latest version of pulse. logging into the admin section. i can barely get a change made before it logs me out and makes me log in again, any clues on this issue and/or how to fix? thanks!

**Comment by ghost** [comment]
Not see this before.

Could be sessions specific.

- Where are you hosting the site?
- can you attach your logs? (settings > extend > logs)

Thanks

**Comment by pulsecmsuser** [comment]
Just deleted everything and reinstalled. It is still rapidly logging me out of admin. Here is the first error log post reinstall:

 

error_log_2018_12_10

[10-Dec-2018 14:59:21 Asia/Tokyo] PHP Warning: fileperms(): stat failed for /home/fmcw/public_html/learn/pulsecore/storage/config.json in /home/fmcw/public_html/learn/admin/install.php on line 322
[10-Dec-2018 14:59:21 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: Unable to find configuration file in /home/fmcw/public_html/learn/pulsecore/dbc.php:12
Stack trace:
#0 /home/fmcw/public_html/learn/pulsecore/wedge/config.php(246): pulsecore\invariant(false, 'Unable to find ...')
#1 /home/fmcw/public_html/learn/pulsecore/wedge/config.php(288): pulsecore\wedge\config\load_config('/home/fmcw/publ...')
#2 /home/fmcw/public_html/learn/config.php(72): pulsecore\wedge\config\wedge_config()
#3 /home/fmcw/public_html/learn/index.php(7): require_once('/home/fmcw/publ...')
#4 {main}
thrown in /home/fmcw/public_html/learn/pulsecore/dbc.php on line 12
[10-Dec-2018 15:00:28 Asia/Tokyo] PHP Warning: file_get_contents(/home/fmcw/public_html/learn/content/blocks/test1.txt): failed to open stream: No such file or directory in /home/fmcw/public_html/learn/pulsecore/store/block/item.php on line 161
[10-Dec-2018 15:00:28 Asia/Tokyo] PHP Fatal error: Uncaught LogicException: A pre-condition has failed in /home/fmcw/public_html/learn/pulsecore/dbc.php:12
Stack trace:
#0 /home/fmcw/public_html/learn/pulsecore/dbc.php(44): pulsecore\invariant(false, 'A pre-condition...')
#1 /home/fmcw/public_html/learn/pulsecore/store/block/item.php(232): pulsecore\pre_condition(false)
#2 /home/fmcw/public_html/learn/pulsecore/store/block/item.php(163): pulsecore\store\block\Item->unpickle(false)
#3 /home/fmcw/public_html/learn/pulsecore/page/end_point.php(38): pulsecore\store\block\Item->load('/home/fmcw/publ...')
#4 /home/fmcw/public_html/learn/pulsecore/page/end_point.php(110): pulsecore\page\end_point\load_block('blocks/test1')
#5 /home/fmcw/public_html/learn/end_point.php(30): pulsecore\page\end_point\process(Array, Array, Array)
#6 {main}
thrown in /home/fmcw/public_html/learn/pulsecore/dbc.php on line 12
[10-Dec-2018 15:00:28 Asia/Tokyo] PHP Warning: include(content/blocks/cpywrt.txt): failed to open stream: No such file or directory in /home/fmcw/public_html/learn/template/layout.php on line 102
[10-Dec-2018 15:00:28 Asia/Tokyo] PHP Warning: include(content/blocks/cpywrt.txt): failed to open stream: No such file or directory in /home/fmcw/public_html/learn/template/layout.php on line 102
[10-Dec-2018 15:00:28 Asia/Tokyo] PHP Warning: include(): Failed opening 'content/blocks/cpywrt.txt' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/fmcw/public_html/learn/template/layout.php on line 102
[10-Dec-2018 15:01:00 Asia/Tokyo] PHP Warning: include(content/blocks/cpywrt.txt): failed to open stream: No such file or directory in /home/fmcw/public_html/learn/template/layout.php on line 102
[10-Dec-2018 15:01:00 Asia/Tokyo] PHP Warning: include(content/blocks/cpywrt.txt): failed to open stream: No such file or directory in /home/fmcw/public_html/learn/template/layout.php on line 102
[10-Dec-2018 15:01:00 Asia/Tokyo] PHP Warning: include(): Failed opening 'content/blocks/cpywrt.txt' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /home/fmcw/public_html/learn/template/layout.php on line 102

**Comment by pulsecmsuser** [comment]
I’ve been sending follow up email replies, but, then I realized, I’m not sure if you are receiving them… Do you get emails that are replies sent to the github address? If so, please reply to let me know if you got this email. Thanks!!

**Comment by ghost** [comment]
Thanks for the logs - we'll need to investigate this

**Comment by pulsecmsuser** [comment]
Thanks again. Like I said… completely uninstalled and reinstalled. Rapid logouts still happening.

**Comment by pulsecmsuser** [comment]
I just had it log me out multiple times. Here are the errors:

 

[11-Dec-2018 00:16:27 America/New_York] PHP Notice: Undefined index: meta_access_user_group in /home/fmcw/public_html/learn/admin/inc/open.php on line 168
[11-Dec-2018 00:18:53 America/New_York] PHP Notice: Undefined index: meta_access_user_group in /home/fmcw/public_html/learn/admin/inc/open.php on line 168
[11-Dec-2018 00:18:57 America/New_York] PHP Notice: Undefined index: meta_access_user_group in /home/fmcw/public_html/learn/admin/inc/open.php on line 168
[11-Dec-2018 00:19:06 America/New_York] PHP Notice: Undefined index: meta_access_user_group in /home/fmcw/public_html/learn/admin/inc/open.php on line 116

**Comment by ghost** [comment]
- Logout too quick - bug fix and regenerate session ID
This is added in the next 5.2.2 version :)

**Comment by ghost** [comment]
5.2.2 will be out in the first few days of January and this fix is included :)
